# Generated by Django 4.1.7 on 2023-03-30 09:02

from django.db import migrations, models
import gymstats.models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="describable",
            name="image",
            field=models.ImageField(
                default=None, upload_to=gymstats.models.Describable.location
            ),
            preserve_default=False,
        ),
    ]
