# Generated by Django 4.1.7 on 2023-03-30 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0002_describable_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "try_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gymstats.try",
                    ),
                ),
            ],
            bases=("gymstats.try",),
        ),
        migrations.RenameModel(
            old_name="Success",
            new_name="Top",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="session",
            name="arrival_time",
        ),
        migrations.AddField(
            model_name="gym",
            name="abv",
            field=models.CharField(default="BON", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="duration",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
