# Generated by Django 4.1.7 on 2023-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0004_try_climber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="try",
            name="climber",
        ),
        migrations.AlterField(
            model_name="session",
            name="alcohol",
            field=models.IntegerField(
                verbose_name="alcohol consumption the day before"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="sleep",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                verbose_name="sleeping hours the night before",
            ),
        ),
    ]
