# Generated by Django 4.1.7 on 2023-03-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0005_remove_try_climber_alter_session_alcohol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="try",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tried",
                to="gymstats.session",
            ),
        ),
    ]
