# Generated by Django 4.1.7 on 2023-03-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0006_alter_try_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="climbers",
        ),
        migrations.AddField(
            model_name="session",
            name="climber",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="gymstats.climber",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="partners",
            field=models.ManyToManyField(related_name="was_at", to="gymstats.climber"),
        ),
        migrations.AlterField(
            model_name="try",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gymstats.session"
            ),
        ),
    ]
