# Generated by Django 4.1.7 on 2023-03-31 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0007_remove_session_climbers_session_climber_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Failure",
        ),
        migrations.DeleteModel(
            name="Top",
        ),
        migrations.DeleteModel(
            name="Try",
        ),
        migrations.DeleteModel(
            name="Zone",
        ),
    ]
