# Generated by Django 4.1.7 on 2023-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0010_alter_describable_image_alter_problem_footwork_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="fear",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (0, "Execrable"),
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Somewhat Bad"),
                    (4, "Average"),
                    (5, "Somewhat Good"),
                    (6, "Good"),
                    (7, "Very Good"),
                    (8, "Great"),
                    (9, "Fantastic"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="motivation",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (0, "Execrable"),
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Somewhat Bad"),
                    (4, "Average"),
                    (5, "Somewhat Good"),
                    (6, "Good"),
                    (7, "Very Good"),
                    (8, "Great"),
                    (9, "Fantastic"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="overall_grade",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (0, "Execrable"),
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Somewhat Bad"),
                    (4, "Average"),
                    (5, "Somewhat Good"),
                    (6, "Good"),
                    (7, "Very Good"),
                    (8, "Great"),
                    (9, "Fantastic"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="partners",
            field=models.ManyToManyField(
                blank=True, related_name="was_at", to="gymstats.climber"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="strength",
            field=models.IntegerField(
                choices=[
                    (-1, "Unknown"),
                    (0, "Execrable"),
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Somewhat Bad"),
                    (4, "Average"),
                    (5, "Somewhat Good"),
                    (6, "Good"),
                    (7, "Very Good"),
                    (8, "Great"),
                    (9, "Fantastic"),
                ]
            ),
        ),
    ]
