# Generated by Django 4.1.7 on 2023-04-14 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0012_alter_failure_options_alter_problem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["-date_added", "grade"]},
        ),
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, "Not Rated"),
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Average"),
                    (4, "Cool"),
                    (5, "Very Cool"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
