# Generated by Django 4.1.7 on 2023-04-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0013_alter_problem_options_review_date_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_id", models.IntegerField()),
                ("map", models.ImageField(blank=True, upload_to="sector-maps")),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gymstats.gym"
                    ),
                ),
                ("wall_types", models.ManyToManyField(to="gymstats.problemtype")),
            ],
        ),
        migrations.AddField(
            model_name="problem",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gymstats.sector",
            ),
        ),
    ]
