# Generated by Django 4.1.7 on 2023-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0014_problem_removed_sector_problem_sector"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gym",
            old_name="location",
            new_name="city",
        ),
        migrations.AlterField(
            model_name="sector",
            name="map",
            field=models.ImageField(blank=True, upload_to="sectors-maps"),
        ),
    ]
