# Generated by Django 4.1.7 on 2023-05-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0016_gym_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="RIC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Average"),
                            (4, "High"),
                            (5, "Very High"),
                        ]
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Average"),
                            (4, "High"),
                            (5, "Very High"),
                        ]
                    ),
                ),
                (
                    "complexity",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Average"),
                            (4, "High"),
                            (5, "Very High"),
                        ]
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gymstats.problem",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gymstats.climber",
                    ),
                ),
            ],
        ),
    ]
