# Generated by Django 4.1.7 on 2023-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0018_climber_mail_climber_picture_climber_pwd_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="climber",
            old_name="week_hard_boulder_target",
            new_name="month_hard_boulder_target",
        ),
        migrations.RenameField(
            model_name="climber",
            old_name="week_hour_target",
            new_name="month_hour_target",
        ),
        migrations.AlterField(
            model_name="hardboulderthreshold",
            name="grade_threshold",
            field=models.CharField(max_length=20),
        ),
    ]
