# Generated by Django 4.1.7 on 2023-06-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0020_climber_my gyms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="climber",
            name="My Gyms",
        ),
        migrations.AddField(
            model_name="climber",
            name="preferred_gyms",
            field=models.ManyToManyField(
                blank=True, to="gymstats.gym", verbose_name="My Gyms"
            ),
        ),
    ]
