# Generated by Django 4.1.7 on 2023-06-30 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gymstats", "0021_remove_climber_my gyms_climber_preferred_gyms"),
    ]

    operations = [
        migrations.AddField(
            model_name="climber",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
