# Generated by Django 4.1.7 on 2023-06-30 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0023_remove_climber_pwd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="climber",
            name="mail",
        ),
    ]
