# Generated by Django 4.1.7 on 2023-10-01 10:33

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0025_intervalstatistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    location_field.models.plain.PlainLocationField(max_length=63),
                ),
                ("name", models.CharField(max_length=100)),
                ("nearest_city", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gym",
            name="name",
            field=models.CharField(default="coucou", max_length=100),
            preserve_default=False,
        ),
    ]
