# Generated by Django 4.1.7 on 2023-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0027_rename_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="indoorsector",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
