# Generated by Django 4.1.7 on 2023-10-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0028_indoorsector_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orientation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="OutdoorSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map", models.ImageField(blank=True, upload_to="sectors-maps")),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "crag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gymstats.crag"
                    ),
                ),
                (
                    "orientations",
                    models.ManyToManyField(blank=True, to="gymstats.orientation"),
                ),
                ("wall_types", models.ManyToManyField(to="gymstats.problemtype")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
