# Generated by Django 4.1.7 on 2023-10-08 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0032_rename_problemmethod_climbingmove_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indoorproblem",
            old_name="problem_method",
            new_name="moves",
        ),
        migrations.RenameField(
            model_name="indoorproblem",
            old_name="problem_type",
            new_name="wall_angle",
        ),
    ]
