# Generated by Django 4.1.7 on 2023-11-01 16:18

from django.db import migrations, models
import django.db.models.deletion
import gymstats.models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0033_rename_problem_method_indoorproblem_moves_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimbAttribute",
            fields=[
                (
                    "describable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gymstats.describable",
                    ),
                ),
            ],
            bases=("gymstats.describable",),
        ),
        migrations.CreateModel(
            name="ClimbType",
            fields=[
                (
                    "describable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gymstats.describable",
                    ),
                ),
            ],
            bases=("gymstats.describable",),
        ),
        migrations.RenameField(
            model_name="indoorsector",
            old_name="wall_types",
            new_name="wall_angles",
        ),
        migrations.RenameField(
            model_name="outdoorsector",
            old_name="wall_types",
            new_name="wall_angles",
        ),
        migrations.CreateModel(
            name="OutdoorProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=10)),
                (
                    "picture",
                    models.ImageField(
                        upload_to=gymstats.models.Climbable.upload_picture
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "climb_attr",
                    models.ManyToManyField(blank=True, to="gymstats.climbattribute"),
                ),
                (
                    "footwork",
                    models.ManyToManyField(blank=True, to="gymstats.footwork"),
                ),
                (
                    "hand_holds",
                    models.ManyToManyField(blank=True, to="gymstats.handhold"),
                ),
                (
                    "moves",
                    models.ManyToManyField(blank=True, to="gymstats.climbingmove"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gymstats.outdoorsector",
                    ),
                ),
                (
                    "wall_angle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gymstats.wallangle",
                    ),
                ),
            ],
            options={
                "ordering": ["grade"],
            },
        ),
        migrations.AddField(
            model_name="indoorproblem",
            name="climb_attr",
            field=models.ManyToManyField(blank=True, to="gymstats.climbattribute"),
        ),
        migrations.AddField(
            model_name="indoorsector",
            name="climb_attrs",
            field=models.ManyToManyField(blank=True, to="gymstats.climbattribute"),
        ),
        migrations.AddField(
            model_name="indoorsector",
            name="climb_types",
            field=models.ManyToManyField(blank=True, to="gymstats.climbtype"),
        ),
        migrations.AddField(
            model_name="outdoorsector",
            name="climb_attrs",
            field=models.ManyToManyField(blank=True, to="gymstats.climbattribute"),
        ),
        migrations.AddField(
            model_name="outdoorsector",
            name="climb_types",
            field=models.ManyToManyField(blank=True, to="gymstats.climbtype"),
        ),
    ]
