# Generated by Django 4.1.7 on 2023-11-01 16:52

from django.db import migrations, models
import django.db.models.deletion
import gymstats.models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0034_climbattribute_climbtype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewClimbable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=10)),
                (
                    "picture",
                    models.ImageField(
                        upload_to=gymstats.models.NewClimbable.upload_picture
                    ),
                ),
                (
                    "climb_attr",
                    models.ManyToManyField(blank=True, to="gymstats.climbattribute"),
                ),
                (
                    "moves",
                    models.ManyToManyField(blank=True, to="gymstats.climbingmove"),
                ),
                (
                    "wall_angle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gymstats.wallangle",
                    ),
                ),
            ],
        ),
    ]
