# Generated by Django 4.1.7 on 2023-11-01 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0036_indoorproblem_climbable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indoorproblem",
            name="climbable",
        ),
        migrations.DeleteModel(
            name="NewClimbable",
        ),
    ]
