# Generated by Django 4.1.7 on 2023-11-01 17:29

from django.db import migrations, models
import django.db.models.deletion
import gymstats.models


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0037_remove_indoorproblem_climbable_delete_newclimbable"),
    ]

    operations = [
        migrations.CreateModel(
            name="NC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=10)),
                (
                    "picture",
                    models.ImageField(upload_to=gymstats.models.Climbable.upload_picture),
                ),
                (
                    "climb_attr",
                    models.ManyToManyField(blank=True, to="gymstats.climbattribute"),
                ),
                (
                    "moves",
                    models.ManyToManyField(blank=True, to="gymstats.climbingmove"),
                ),
                (
                    "wall_angle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gymstats.wallangle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="indoorproblem",
            name="climbable",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specific",
                to="gymstats.nc1",
            ),
        ),
    ]
