# Generated by Django 4.1.7 on 2023-11-01 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0040_rename_nc1_climbable_crux"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IndoorProblem",
            new_name="IndoorBoulder",
        ),
        migrations.RenameModel(
            old_name="OutdoorProblem",
            new_name="OutdoorBoulder",
        ),
    ]
