# Generated by Django 4.1.7 on 2023-11-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gymstats", "0042_climbable_climb_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indoorboulder",
            name="climbable",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="gymstats.climbable"
            ),
        ),
    ]
